complexity:
    LongParameterList:
        active: false
    LongMethod:
        active: false

style:
    MagicNumber:
        ignorePropertyDeclaration: true
        ignoreLocalVariableDeclaration: true
        ignoreCompanionObjectPropertyDeclaration: true
    UnusedPrivateMember:
        ignoreAnnotated: [ 'Preview' ]
    NewLineAtEndOfFile:
        active: false

naming:
    TopLevelPropertyNaming:
        constantPattern: '[A-Z][_A-Za-z0-9]*'
    FunctionNaming:
        ignoreAnnotated: [ 'Composable' ]