[versions]
# Gradle Versions
kotlin-gradle-plugin = "1.8.0"
android-gradle-plugin = "8.1.0"

# Config Versions
compileSdk = "33"
minSdk = "26"
targetSdk = "33"
versionCode = "1"
versionName = "1.0"
jvmTarget = "17"
kotlinCompilerExtensionVersion = "1.4.0"

# Library Versions
androidx-core = "1.9.0"
androidx-lifecycle-runtime = "2.6.2"
androidx-appcompat = "1.6.1"
android-material = "1.9.0"
androidx-constraintlayout = "2.1.4"
androidx-navigation = "2.5.3"

activity-compose = "1.7.2"
compose-ui = "1.3.3"
compose-material3 = "1.0.1"

junit = "4.13.2"
androidx-junit = "1.1.5"
androidx-expresso = "3.5.1"

compose-ui-test-junit4 = "1.5.1"

compose-ui-tooling = "1.3.3"


[plugins]
# build.gradle (project module)
android-application-gradle = { id = "com.android.application", version.ref = "android-gradle-plugin" }
kotlin-gradle = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin-gradle-plugin" }
android-gradle = { id = "com.android.library", version.ref = "android-gradle-plugin" }

[libraries]
# Android Library
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle-runtime" }

# Compose Library
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
compose-ui = { module = "androidx.activity:activity-compose", version.ref = "compose-ui" }
compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics", version.ref = "compose-ui" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose-ui" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "compose-material3" }
compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "androidx-navigation"}

# Test Library
junit = { module = "junit:junit", version.ref = "junit" }

# Android Test Library
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-junit" }
androidx-espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-expresso" }
compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose-ui-test-junit4" }

# Debug Library
compose-ui-tooling-debug = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose-ui-tooling" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose-ui" }

[bundles]
# Android
android-library = ["androidx-core-ktx", "androidx-lifecycle-runtime-ktx"]
compose = ["activity-compose", "compose-ui", "compose-ui-graphics", "compose-ui-tooling-preview", "compose-material3", "compose-navigation"]

test = ["junit"]
android-test = ["androidx-junit", "androidx-espresso"]
android-compose-test = ["compose-ui-test-junit4"]

compose-debug = ["compose-ui-tooling-debug", "compose-ui-test-manifest"]